# Generated by Erlang.mk. Edit at your own risk!

ERTS_INCLUDE_DIR ?= /usr/lib/erlang/erts-13.2/include/
ERL_INTERFACE_INCLUDE_DIR ?= /usr/lib/erlang/lib/erl_interface-5.3.1/include
ERL_INTERFACE_LIB_DIR ?= /usr/lib/erlang/lib/erl_interface-5.3.1/lib
ERTS_DIR ?= /usr/lib/erlang/lib/erts-13.2
